export const SHOW_ADD_BUDGET_MODAL = 'SHOW_ADD_BUDGET_MODAL';
export const SHOW_TRANSACTION_MODAL = 'SHOW_TRANSACTION_MODAL';

export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const UPDATE_TRANSACTIONS = 'UPDATE_TRANSACTIONS';

export const RESET_UPDATED_BUDGET = 'RESET_UPDATED_BUDGET';
export const RESET_UPDATED_TRANSACTIONS = 'RESET_UPDATED_TRANSACTIONS';

export const SET_BUDGETS = 'SET_BUDGETS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_ERRORS = 'SET_ERRORS';
export const SET_PAGINATION_META = 'SET_PAGINATION_META';

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_ANALYTICS = 'GET_ANALYTICS';
