export const SET_BUDGETS = 'SET_BUDGETS';
export const SHOW_MODAL = 'SHOW_MODAL';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const RESET_UPDATED_BUDGET = 'RESET_UPDATED_BUDGET';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_ERRORS = 'SET_ERRORS';
